on:
  pull_request:
  push:
    branches:
    - main
    - 'releases/*'
jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run performance tests
      uses: swissspidy/wp-performance-action@main
      with:
        plugins: |
          ./
        urls: |
          /